apiVersion: v1
kind: Service
metadata:
  name: bs-app1
  namespace: bs-apps
  labels:
    app: bs-app1
spec:
  type: ClusterIP
  selector:
    app: bs-app1
  ports:
    - port: 80
      targetPort: 8080