node {
    def app

    stage('Clone repository') {
      
        checkout scm
    }

    stage('Build image') {
  
       app = docker.build("mashnoor/bs-app2", "-f ./task1/app2/build/Dockerfile ./task1/app2")
    }

    stage('Push image') {
        
        
        docker.withRegistry('', 'dockerhub') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
            
        }
    }
}