version: "3.8"


services:
  jenkins_server:
    build:
      context: .
    networks:
      - jenkins
    container_name: JenkinsServer
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
    - "8090:8080"
    - "50000:50000"
    volumes:
    - jenkins-docker-certs:/certs/client
    - jenkins-home:/var/jenkins_home
    - jenkins-docker-certs:/extras

  jenkins_docker:
    image: docker:dind
    networks:
      jenkins:
        aliases:
          - docker
    container_name: JenkinsDocker
    privileged: true
    environment:
    - DOCKER_TLS_CERTDIR=/certs
    ports:
    - "2376:2376"
    volumes:
    - jenkins-docker-certs:/certs/client
    - jenkins-home:/var/jenkins_home
    - jenkins-docker-certs:/extras


volumes:
  jenkins-home:
  jenkis-extras:
  jenkins-docker-certs:



networks:
  jenkins:
    driver: bridge