
version: '2'

services:
  jenkins:
    image: docker.io/bitnami/jenkins:latest
    ports:
      - '8090:8080'
    environment:
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=password
    volumes:
      - 'jenkins_data:/bitnami/jenkins'

volumes:
  jenkins_data:
    driver: local