apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: default

data:  
  default: |
      server {  
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html index.htm;
        location /app1 {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://bs-app1/;
        }
        location /app2 {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://bs-app2/;
        }
      }

