apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: bs-apps
  labels:
    app: nginx

spec:
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
   
      tolerations:
      - key: "app-name"
        operator: "Equal"
        value: "bs-app1"
        effect: "NoSchedule"
   
      containers:
      - name: nginx-app
        image: nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1m"
            memory: "100Mi"
          limits:
            cpu: "4000m"
            memory: "4096Mi"

        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-config
          subPath: default

        env:
        - name: COUNTER
          value: "9"

      volumes:
      - name: nginx-config
        configMap:
          name: nginx
