apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: bs-apps
  labels:
    app: nginx
spec:
  selector:    
    app: nginx
  type: NodePort
  ports:  
  - name: http-nginx
    port: 8080
    targetPort: 80
    # nodePort: 30080
    protocol: TCP