apiVersion: v1
kind: Service
metadata:
  name: bs-app2
  namespace: default
  labels:
    app: bs-app2
spec:
  type: ClusterIP
  selector:
    app: bs-app2
  ports:
    - port: 80
      targetPort: 8080