apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: bs-apps
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: nginx-gateway
      protocol: HTTP
    hosts:
    - "*"
